// Begin - Disable XML Comment Warnings for generated code
#pragma warning disable 1591

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace sdsd {
    using System.Xml.Serialization;
    using System.Collections;
    using System.Collections.Generic;

    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/unityLogistics.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/unityLogistics.xsd", IsNullable=false)]
    public partial class unity {
        
        private int currentModuleField;
        
        private bool currentModuleFieldSpecified;
        
        private string nextLectureField;
        
        private string currentActivityField;
        
        private List<string> notesField = new List<string>();
        
        /// <remarks/>
        public int currentModule {
            get {
                return this.currentModuleField;
            }
            set {
                this.currentModuleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool currentModuleSpecified {
            get {
                return this.currentModuleFieldSpecified;
            }
            set {
                this.currentModuleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string nextLecture {
            get {
                return this.nextLectureField;
            }
            set {
                this.nextLectureField = value;
            }
        }
        
        /// <remarks/>
        public string currentActivity {
            get {
                return this.currentActivityField;
            }
            set {
                this.currentActivityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("note", IsNullable=false)]
        public string[] notes {
            get {
                return (this.notesField == null ? null : this.notesField.ToArray());
            }
            set {
                this.notesField = (value == null) ? null : new List<string>(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore]
        public List<string> notesList {
            get {
                return this.notesField;
            }
        }

    }
}

// End - Disable XML Comment Warnings for generated code
#pragma warning restore 1591