// Begin - Disable XML Comment Warnings for generated code
#pragma warning disable 1591

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace SampleXsdGenerator {
    using System.Xml.Serialization;
    using System.Collections;
    using System.Collections.Generic;

    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cfp.intuit.com/service/taxreturn")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://cfp.intuit.com/service/taxreturn", IsNullable=false)]
    public partial class GetReturnRequest : RequestMessage {
        
        private string documentOwnerIdField;
        
        private string taxDocumentIdField;
        
        private System.DateTime versionField;
        
        private bool versionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string documentOwnerId {
            get {
                return this.documentOwnerIdField;
            }
            set {
                this.documentOwnerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string taxDocumentId {
            get {
                return this.taxDocumentIdField;
            }
            set {
                this.taxDocumentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool versionSpecified {
            get {
                return this.versionFieldSpecified;
            }
            set {
                this.versionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cfp.intuit.com/base")]
    public abstract partial class RequestMessage : Message {
        
        private string sessionTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sessionToken {
            get {
                return this.sessionTokenField;
            }
            set {
                this.sessionTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponseMessage))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cfp.intuit.com/base")]
    public abstract partial class Message {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cfp.intuit.com/service/taxreturn")]
    public partial class KeyValue {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cfp.intuit.com/service/taxreturn")]
    public partial class DocumentInformation {
        
        private string keyField;
        
        private FormatEnum formatField;
        
        private bool formatFieldSpecified;
        
        private string nameField;
        
        private string taxYearField;
        
        private AppSku appSkuField;
        
        private bool appSkuFieldSpecified;
        
        private AppId applicationIdField;
        
        private bool applicationIdFieldSpecified;
        
        private System.DateTime versionField;
        
        private bool versionFieldSpecified;
        
        private string deviceIdField;
        
        private string deviceNameField;
        
        private List<KeyValue> attributesField = new List<KeyValue>();
        
        private System.DateTime baseVersionTimestampField;
        
        private bool baseVersionTimestampFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FormatEnum format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool formatSpecified {
            get {
                return this.formatFieldSpecified;
            }
            set {
                this.formatFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string taxYear {
            get {
                return this.taxYearField;
            }
            set {
                this.taxYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AppSku appSku {
            get {
                return this.appSkuField;
            }
            set {
                this.appSkuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool appSkuSpecified {
            get {
                return this.appSkuFieldSpecified;
            }
            set {
                this.appSkuFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AppId applicationId {
            get {
                return this.applicationIdField;
            }
            set {
                this.applicationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool applicationIdSpecified {
            get {
                return this.applicationIdFieldSpecified;
            }
            set {
                this.applicationIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool versionSpecified {
            get {
                return this.versionFieldSpecified;
            }
            set {
                this.versionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string deviceId {
            get {
                return this.deviceIdField;
            }
            set {
                this.deviceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string deviceName {
            get {
                return this.deviceNameField;
            }
            set {
                this.deviceNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("attribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public KeyValue[] attributes {
            get {
                return (this.attributesField == null ? null : this.attributesField.ToArray());
            }
            set {
                this.attributesField = (value == null) ? null : new List<KeyValue>(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore]
        public List<KeyValue> attributesList {
            get {
                return this.attributesField;
            }
        }

        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime baseVersionTimestamp {
            get {
                return this.baseVersionTimestampField;
            }
            set {
                this.baseVersionTimestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool baseVersionTimestampSpecified {
            get {
                return this.baseVersionTimestampFieldSpecified;
            }
            set {
                this.baseVersionTimestampFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cfp.intuit.com/service/taxreturn/types")]
    public enum FormatEnum {
        
        /// <remarks/>
        taxml,
        
        /// <remarks/>
        formml,
        
        /// <remarks/>
        pdf,
        
        /// <remarks/>
        ceml,
        
        /// <remarks/>
        tcml,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cfp.intuit.com/service/taxreturn/types")]
    public enum AppSku {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("16")]
        Item16,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("32")]
        Item32,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("512")]
        Item512,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("801")]
        Item801,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("802")]
        Item802,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2048")]
        Item2048,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4096")]
        Item4096,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8192")]
        Item8192,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("16384")]
        Item16384,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cfp.intuit.com/service/taxreturn/types")]
    public enum AppId {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Intuit.cg.dataplatform")]
        Intuitcgdataplatform,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("intuit.cg.efs.efe")]
        intuitcgefsefe,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("intuit.cg.dataservices")]
        intuitcgdataservices,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("intuit.cg.cfp.services")]
        intuitcgcfpservices,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Intuit.cg.pf.mint")]
        Intuitcgpfmint,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Intuit.ctg.tto.platform")]
        Intuitctgttoplatform,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Intuit.ctg.ido")]
        Intuitctgido,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Intuit.ctg.instantreturn.iphoneapp")]
        Intuitctginstantreturniphoneapp,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Intuit.cg.cid.service")]
        Intuitcgcidservice,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Intuit.cg.nue")]
        Intuitcgnue,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Intuit.cg.ttn.platform")]
        Intuitcgttnplatform,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Intuit.cg.ttn.ipad")]
        Intuitcgttnipad,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Intuit.iit.wcg.platform ")]
        Intuitiitwcgplatform,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Intuit.wcg.turbotax.csr")]
        Intuitwcgturbotaxcsr,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Intuit.cg.turbotax.salesforce")]
        Intuitcgturbotaxsalesforce,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Intuit.cg.myturbotax")]
        Intuitcgmyturbotax,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Intuit.cg.cfp.opstool")]
        Intuitcgcfpopstool,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Intuit.gbd.cfp.sp")]
        Intuitgbdcfpsp,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cfp.intuit.com/base")]
    public abstract partial class ResponseMessage : Message {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cfp.intuit.com/service/taxreturn")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://cfp.intuit.com/service/taxreturn", IsNullable=false)]
    public partial class GetReturnResponse : ResponseMessage {
        
        private DocumentInformation documentInformationField;
        
        private List<byte> documentField = new List<byte>();
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DocumentInformation documentInformation {
            get {
                return this.documentInformationField;
            }
            set {
                this.documentInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] document {
            get {
                return (this.documentField == null ? null : this.documentField.ToArray());
            }
            set {
                this.documentField = (value == null) ? null : new List<byte>(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore]
        public List<byte> documentList {
            get {
                return this.documentField;
            }
        }

    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cfp.intuit.com/service/taxreturn")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://cfp.intuit.com/service/taxreturn", IsNullable=false)]
    public partial class PutReturnRequest : RequestMessage {
        
        private string documentOwnerIdField;
        
        private List<byte> documentField = new List<byte>();
        
        private DocumentInformation documentInformationField;
        
        private System.DateTime forceField;
        
        private bool forceFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string documentOwnerId {
            get {
                return this.documentOwnerIdField;
            }
            set {
                this.documentOwnerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] document {
            get {
                return (this.documentField == null ? null : this.documentField.ToArray());
            }
            set {
                this.documentField = (value == null) ? null : new List<byte>(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore]
        public List<byte> documentList {
            get {
                return this.documentField;
            }
        }

        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DocumentInformation documentInformation {
            get {
                return this.documentInformationField;
            }
            set {
                this.documentInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime force {
            get {
                return this.forceField;
            }
            set {
                this.forceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool forceSpecified {
            get {
                return this.forceFieldSpecified;
            }
            set {
                this.forceFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cfp.intuit.com/service/taxreturn")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://cfp.intuit.com/service/taxreturn", IsNullable=false)]
    public partial class PutReturnResponse : ResponseMessage {
        
        private DocumentInformation documentInformationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DocumentInformation documentInformation {
            get {
                return this.documentInformationField;
            }
            set {
                this.documentInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cfp.intuit.com/service/taxreturn")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://cfp.intuit.com/service/taxreturn", IsNullable=false)]
    public partial class DeleteReturnRequest : RequestMessage {
        
        private string documentOwnerIdField;
        
        private string taxDocumentIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string documentOwnerId {
            get {
                return this.documentOwnerIdField;
            }
            set {
                this.documentOwnerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string taxDocumentId {
            get {
                return this.taxDocumentIdField;
            }
            set {
                this.taxDocumentIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cfp.intuit.com/service/taxreturn")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://cfp.intuit.com/service/taxreturn", IsNullable=false)]
    public partial class DeleteReturnResponse : ResponseMessage {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cfp.intuit.com/service/taxreturn")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://cfp.intuit.com/service/taxreturn", IsNullable=false)]
    public partial class ListReturnsRequest : RequestMessage {
        
        private string documentOwnerIdField;
        
        private string taxYearRangeStartField;
        
        private string taxYearRangeEndField;
        
        private FormatEnum formatField;
        
        private bool formatFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string documentOwnerId {
            get {
                return this.documentOwnerIdField;
            }
            set {
                this.documentOwnerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string taxYearRangeStart {
            get {
                return this.taxYearRangeStartField;
            }
            set {
                this.taxYearRangeStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string taxYearRangeEnd {
            get {
                return this.taxYearRangeEndField;
            }
            set {
                this.taxYearRangeEndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FormatEnum format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool formatSpecified {
            get {
                return this.formatFieldSpecified;
            }
            set {
                this.formatFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cfp.intuit.com/service/taxreturn")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://cfp.intuit.com/service/taxreturn", IsNullable=false)]
    public partial class ListReturnsResponse : ResponseMessage {
        
        private List<DocumentInformation> documentInformationListField = new List<DocumentInformation>();
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("documentInformation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DocumentInformation[] documentInformationList {
            get {
                return (this.documentInformationListField == null ? null : this.documentInformationListField.ToArray());
            }
            set {
                this.documentInformationListField = (value == null) ? null : new List<DocumentInformation>(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore]
        public List<DocumentInformation> documentInformationListList {
            get {
                return this.documentInformationListField;
            }
        }

    }
}

// End - Disable XML Comment Warnings for generated code
#pragma warning restore 1591